spring.application.name=api

# Log level configuration
logging.level.root=ERROR 
logging.level.com.chatop=INFO

# Database configuration
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.config.import=optional:file:./local.properties