spring.application.name=api

server.port=3001
# Log level configuration
logging.level.root=ERROR 
logging.level.com.chatop=INFO

# Database configuration
spring.config.import = optional:file:./local.properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql = true