# Application configuration
spring.application.name=api
server.port=3001
app.cors.allowed-origins=http://localhost:4200
app.upload.dir=uploads
app.upload.base-url=http://localhost:3001/images/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Log level configuration
logging.level.root=ERROR 
logging.level.com.chatop=INFO

# Database configuration
spring.config.import = optional:file:./local.properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql = true